// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zYSULEe-LI937Ww9cZ36-LXyQcGjCfs',
    appId: '1:275640151003:web:90cf96760aeaee6de615fe',
    messagingSenderId: '275640151003',
    projectId: 'freshloop-20',
    authDomain: 'freshloop-20.firebaseapp.com',
    storageBucket: 'freshloop-20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAek_0GGzoCPwOQnaaUem5f52qMwEh6wFs',
    appId: '1:275640151003:android:315dfc6d0733f466e615fe',
    messagingSenderId: '275640151003',
    projectId: 'freshloop-20',
    storageBucket: 'freshloop-20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLX-mlgBz88Xg-H3W2CZDmN0urPFM166U',
    appId: '1:275640151003:ios:ee494c63cdd02caee615fe',
    messagingSenderId: '275640151003',
    projectId: 'freshloop-20',
    storageBucket: 'freshloop-20.firebasestorage.app',
    iosBundleId: 'com.example.freshloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLX-mlgBz88Xg-H3W2CZDmN0urPFM166U',
    appId: '1:275640151003:ios:ee494c63cdd02caee615fe',
    messagingSenderId: '275640151003',
    projectId: 'freshloop-20',
    storageBucket: 'freshloop-20.firebasestorage.app',
    iosBundleId: 'com.example.freshloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zYSULEe-LI937Ww9cZ36-LXyQcGjCfs',
    appId: '1:275640151003:web:b7ae9c537fe13783e615fe',
    messagingSenderId: '275640151003',
    projectId: 'freshloop-20',
    authDomain: 'freshloop-20.firebaseapp.com',
    storageBucket: 'freshloop-20.firebasestorage.app',
  );
}
